# Generated by Django 5.2 on 2025-11-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username_persistent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('short_code', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='file.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'indexes': [models.Index(fields=['user', 'file'], name='log_downloa_user_id_e4e359_idx')],
            },
        ),
    ]
